name: 'coverage'
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: npm install and test
      run: |
        npm install
        CI='' npm test
        npm run test-coverage 
      env: 
        TEST_DB_URL: ${{ secrets.TEST_DB_URL }} 
        JWT: ${{ secrets.JWT }}
