name: 'coverage'
on: push
jobs: 
  tests:
    name: "coverage"
    runs-on: ubuntu-latest
    steps:
        - uses: mattallty/jest-github-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DB_URL: ${{ secrets.DB_URL }}
          with:
            working-directory: "./server"
